var Honeybadger = require('honeybadger-js/honeybadger');

Honeybadger.configure({
  apiKey: process.env.HONEYBADGER_API_KEY,
  environment: process.env.RAILS_ENV || 'development',
  revision: process.env.GIT_COMMIT || 'master',
  debug: true
});

const Main = {
  initialize() {
    var helloNode = document.getElementById('helloBtn');
    var throwNode = document.getElementById('throwBtn');

    helloNode.addEventListener('click', (event) => {
      event.preventDefault();
      Main.sayHello();
    });

    throwNode.addEventListener('click', (event) => {
      event.preventDefault();
      Main.throwError();
    });
  },

  sayHello: function () {
    var node = document.getElementById('hello');
    var value = node.innerHTML;
    var hello = 'Hello World';
    console.log(hello);
    node.innerHTML = hello;
  },

  throwError: function() {
    function one() {
      return two();
    }

    function two() {
      return three();
    }

    function three() {
      throw new Error("This is a test error generated by Honeybadger's Rails/Webpacker Example application. https://github.com/honeybadger-io/honeybadger-rails-webpacker-example");
    }

    return one();
  }
};

document.addEventListener('DOMContentLoaded', () => {
  Main.initialize();
});
